name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    permissions:
      contents: write
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run tauri build

      - name: Get version info
        id: version
        run: |
          # Read version from tauri.conf.json
          VERSION=$(cat src-tauri/tauri.conf.json | grep '"version"' | cut -d'"' -f4)
          # Add build metadata
          FULL_VERSION="${VERSION}+build.${{ github.run_number }}"
          # Tag uses clean semantic version
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "FULL_VERSION=$FULL_VERSION" >> $GITHUB_OUTPUT
          echo "TAG_NAME=v$VERSION" >> $GITHUB_OUTPUT

      - name: Package app as zip
        run: |
          cd src-tauri/target/release/bundle/macos
          zip -r "Simple-Notes-v${{ steps.version.outputs.VERSION }}.zip" "Simple Notes.app"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.TAG_NAME }}
          name: Simple Notes ${{ steps.version.outputs.TAG_NAME }}
          body: |
            ## Simple Notes Release ${{ steps.version.outputs.TAG_NAME }}
            
            ### Changes in this Release
            - Auto-generated release from commit ${{ github.sha }}
            
            ### Installation Instructions
            1. Download the `Simple-Notes-v${{ steps.version.outputs.VERSION }}.zip` file
            2. Extract the zip file
            3. Drag `Simple Notes.app` to your Applications folder
            4. Launch Simple Notes from Applications or Spotlight
            
            ### System Requirements
            - macOS 10.15 (Catalina) or later
            - 64-bit Intel or Apple Silicon Mac
            
            ### Features
            - 🍎 Native macOS menubar app
            - 📝 Markdown note editing
            - ☁️ GitHub Gist synchronization
            - 🎨 Clean, modern interface
          files: |
            src-tauri/target/release/bundle/macos/Simple-Notes-v${{ steps.version.outputs.VERSION }}.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}